### ISSUE TITLE
Add support for INTERFACE and IMPLEMENTS in function blocks

### ISSUE THREAD

**Issue by klauer** [klauer/blark#16]
https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/4262436875.html&id=

Also find a better reference for it.

TODO:
- [x] Add support for `IMPLEMENTS` in `FUNCTION_BLOCK`
- [ ] Find better documentation and grammar references for `IMPLEMENTS`
- [x] Add top-level grammar for `INTERFACE` declaration (`interface_declaration`)
- [x] Add declarations under `interface_declaration` for supported grammar (methods, properties)
- [x] Add `INTERFACE` support in the transformers
- [x] Add `INTERFACE` test cases and ensure they round-trip from code->Python dataclasses->code
- [x] Follow up on pytmc support of `.TcIO` files: https://github.com/pcdshub/pytmc/issues/276

**Comment by engineerjoe440** [comment]
I was beginning to look at this item, to see if I might be able to help with it. I do feel a bit confused, so I want to check my understanding. Were you intending to support INTERFACE objects specifically, almost like FUNCTION_BLOCKs, but specifically with the appropriate interface syntax (i.e., no implementation sections). I think what might make sense (at least at the top level) would be to carve out unique `interface_declaration`, `interface_method_declaration`, and `interface_property_declaration` to follow the similarly named FUNCTION_BLOCK items:

![image](https://user-images.githubusercontent.com/33275230/228362451-968d4279-deaf-489b-ac7a-46610309e02a.png)

Am I following your train-of-thought here?

**Comment by klauer** [comment]
Yeah, sorry about the very terse "TODO"-style issue here.

It looks like I added `FUNCTION_BLOCK ... IMPLEMENTS` at some point in the grammar (30bda8eb), so the core of this issue is then supporting library-element-level `INTERFACE` declarations (just as you've laid out above). I'll tweak the original issue text.

There's a bit of investigation to do to properly implement this, I think. And `pytmc` needs a bit of work to parse `TcIO` files and dump out compatible code, too - but that shouldn't stop blark from implementing the `INTERFACE` declaration grammar.

These `INTERFACE` definitions will then be of the form:
```
INTERFACE I_Name [EXTENDS I_Base1, ...]
[METHOD ...]
[PROPERTY ...]
END_INTERFACE
```

From what I understand these can only include `PROPERTY` and `METHOD` (without implementation sections as you've noted). 
Here's some code examples that might be of use while coming up with the grammar:
* https://stackoverflow.com/questions/56213383/if-a-var-input-is-of-interface-type-is-the-value-pass-by-reference-or-pass-by-v (see the actual block of `INTERFACE/END_INTERFACE` there)
* https://github.com/search?q=interface+path%3A%2F.*%5C.tcio%24%2F&type=code (GitHub's search has really improved! This is a great way to find TwinCAT code...)

I'm not sure if any existing parsers work on `INTERFACE` objects (a 5 minute glance at related projects https://github.com/klauer/blark/issues/27 indicates probably not)
