### ISSUE TITLE
Array initializer from TwinCAT documentation fails to parse

### ISSUE THREAD

**Issue by klauer** [klauer/blark#44]
From https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/2530335371.html&id=

```
PROGRAM MAIN
VAR
    fbSample  : FB_Sample(nInitParam := 1) := (nInput := 2, nMyProperty := 3);
    aSample   : ARRAY[1..2] OF FB_Sample[(nInitParam := 4), (nInitParam := 7)]
                            := [(nInput := 5, nMyProperty := 6), (nInput := 8, nMyProperty := 9)];
END_VAR
END_PROGRAM
```

This odd syntax is explained later in the linked documentation page.

**Comment by engineerjoe440** [comment]
Looks like I've run into this in the wild, too... haha! I'm going to start seeing if I can poke around and come up with any solutions. :smile:
