### ISSUE TITLE
Remove `method_statement` from grammar

### ISSUE THREAD

**Issue by klauer** [klauer/blark#61]
> Looks like it's time to get rid of `method_statement` entirely.
>
> `function_call_statement` (using `function_call`) handles everything it does and more, so having both just makes for ambiguity in the grammar.

_Originally posted by @klauer in https://github.com/klauer/blark/pull/59#discussion_r1164761928_

Checklist:
- [ ] Remove `method_statement` from `iec.lark`
- [ ] Remove `MethodStatement` from `blark.transformers`

**Comment by engineerjoe440** [comment]
I actually had some questions about this, so this makes a lot of sense to me. Thank you for your attention to detail, here! :tada:
